# Generated by Django 4.2.4 on 2023-09-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mazmuni',
            field=models.TextField(null=True),
        ),
    ]
